[server]
port="3002"
readTimeout=5
writeTimeout=5
closeTimeout=5

[logger]
file="log.log"

[zipkin]
isEnable=false
host="127.0.0.1"
port="9411"

[database]
type="mysql"
host="127.0.0.1"
dbName="godb"
userName="root"
password="root"